- name: Prepare
  become: true
  hosts: all
  tasks:
    - name: install gentoolkit
      command: "emerge app-portage/gentoolkit"
      args:
        creates: "/usr/bin/equery"
      when: ansible_distribution == "Gentoo"

    - name: install dnsmasq
      package:
        name: dnsmasq
        state: present

    - name: create dnsmasq configuration
      copy:
        content: |
          interface=lo
          bind-interfaces

          server=1.1.1.1
          server=/consul/127.0.0.1#8600

          local-service
          no-poll
          no-resolv

        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644

    - name: enable dnsmasq
      service:
        name: dnsmasq
        enabled: true
        state: started

    - name: create resolv.conf
      copy:
        content: |
          nameserver 127.0.0.1
          search service.consul node.consul
        dest: "/etc/resolv.conf"
        owner: root
        group: root
        mode: 0644

    - name: create consul directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/consul/service.d
        - /opt/consul/config.d
        - /opt/consul/script.d

    - name: create dummy files
      file:
        path: "{{ item }}"
        state: touch
      loop:
        - /opt/consul/service.d/dummy.json
        - /opt/consul/config.d/dummy.json
        - /opt/consul/script.d/dummy.sh
