- name: restart consul
  service:
    name: consul
    state: restarted
  when: not lookup("env", "PACKER_BUILD_NAME") | default("")

- name: reload consul
  service:
    name: consul
    state: reloaded
  when: not lookup("env", "PACKER_BUILD_NAME") | default("")
